### ISSUE TITLE
Real-time updatable Dashboard

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#102]

**Comment by gladky** [comment]
- [ ] make a dashboard updatable
- [ ] update the webservice to handle updates
- [ ] generate updates from context changes
