### ISSUE TITLE
Special instructions: Strip tracker

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#211]
>    * *Strip Tracker*
>       * if the FED supervisor fails: Stop the run and redrecycle tracker
>       * if a tracker TCDS timeout happens during configure step: redrecycle tracker
>       * if APVEs go out-of-sync at the start of the run: Sending a TTC resync command should solve the issue (it might be necessary to retry a few times). If not, stop the run and redrecycle tracker. <br />After the out-of-sync has gone away, it happens from time to time that one the tracker iCl's flicker between ready and busy states. If that's the case, stop the run and redrecycle tracker.
>       * All fragments have S-CRC errors on a FED: Stop the run and redrecycle tracker.
>       * If FED 434 continuously blocks the DAQ at run start with "SyncLoss: Caught exception: exception::MismatchDetected ..." it can be taken out. (K. Rabbertz, 10.09.2015, according to call back from Tracker DOC).
>

**Comment by gladky** [comment]
- [ ] is this up to date?
- [ ] shall we include this in expert? if yes:
    - [ ] where do we take information about FED supervisor failing

**Comment by erikbutz** [comment]
The first issue should be covered by the fact that the tracker L1 FM will go to error, so I don't think we need to explicitly add this. Same for the TCDS supervisor.
The APVe case is covered in https://github.com/cmsdaq/DAQExpert/issues/215, though the point about the flickering we could add, though I haven't checked if this still happens. 

CRC errors: I have not seen CRC errors on FEDs in a long time and S-CRC errors in principle are in the realm of the DAQ, so I am not sure what the best course of action is in this case. 

FED 434: we should NOT add these instructions to the DAQ expert and instead remove them.

**Comment by hsakulin** [comment]
I would remove the instructions about S-CRC errors. We are not aware that this case happens and if it is an SLINK CRC it is not clear to me that red recycle of Tracker would fix this.
